name 'jira_db'
maintainer 'Tim Beeler'
maintainer_email 'timothybeeler@me.com'
license 'all_rights'
description 'Installs/Configures jira_db'
long_description 'Installs/Configures jira_db'
version '0.0.1'
